export enum AuditAction {
  GRIEVANCE_SUBMITTED = "GRIEVANCE_SUBMITTED",
  GRIEVANCE_ACKNOWLEDGED = "GRIEVANCE_ACKNOWLEDGED",
  GRIEVANCE_ASSIGNED = "GRIEVANCE_ASSIGNED",
  GRIEVANCE_REASSIGNED = "GRIEVANCE_REASSIGNED",
  GRIEVANCE_STATUS_CHANGED = "GRIEVANCE_STATUS_CHANGED",
  GRIEVANCE_UPDATED = "GRIEVANCE_UPDATED",
  GRIEVANCE_RESOLVED = "GRIEVANCE_RESOLVED",
  GRIEVANCE_CLOSED = "GRIEVANCE_CLOSED",
  GRIEVANCE_REJECTED = "GRIEVANCE_REJECTED",
  GRIEVANCE_SOFT_DELETED = "GRIEVANCE_SOFT_DELETED",
  GRIEVANCE_RESTORED = "GRIEVANCE_RESTORED",
  GRIEVANCE_PURGED = "GRIEVANCE_PURGED",
  PUBLIC_UPDATE_ADDED = "PUBLIC_UPDATE_ADDED",
  INTERNAL_NOTE_ADDED = "INTERNAL_NOTE_ADDED",
  ATTACHMENT_ADDED = "ATTACHMENT_ADDED",
  USER_CREATED = "USER_CREATED",
  USER_UPDATED = "USER_UPDATED",
  PROFILE_UPDATED = "PROFILE_UPDATED",
  USER_DEACTIVATED = "USER_DEACTIVATED",
  USER_SOFT_DELETED = "USER_SOFT_DELETED",
  USER_RESTORED = "USER_RESTORED",
  USER_PURGED = "USER_PURGED",
  INVITATION_SENT = "INVITATION_SENT",
  INVITATION_ACCEPTED = "INVITATION_ACCEPTED",
  INVITATION_SOFT_DELETED = "INVITATION_SOFT_DELETED",
  INVITATION_RESTORED = "INVITATION_RESTORED",
  INVITATION_PURGED = "INVITATION_PURGED",
  CATEGORY_CREATED = "CATEGORY_CREATED",
  CATEGORY_UPDATED = "CATEGORY_UPDATED",
  CATEGORY_DEACTIVATED = "CATEGORY_DEACTIVATED",
  CATEGORY_SOFT_DELETED = "CATEGORY_SOFT_DELETED",
  CATEGORY_RESTORED = "CATEGORY_RESTORED",
  CATEGORY_PURGED = "CATEGORY_PURGED",
  SUBCOUNTY_CREATED = "SUBCOUNTY_CREATED",
  SUBCOUNTY_UPDATED = "SUBCOUNTY_UPDATED",
  SUBCOUNTY_DEACTIVATED = "SUBCOUNTY_DEACTIVATED",
  SUBCOUNTY_SOFT_DELETED = "SUBCOUNTY_SOFT_DELETED",
  SUBCOUNTY_RESTORED = "SUBCOUNTY_RESTORED",
  SUBCOUNTY_PURGED = "SUBCOUNTY_PURGED",
  WARD_CREATED = "WARD_CREATED",
  WARD_UPDATED = "WARD_UPDATED",
  WARD_DEACTIVATED = "WARD_DEACTIVATED",
  WARD_SOFT_DELETED = "WARD_SOFT_DELETED",
  WARD_RESTORED = "WARD_RESTORED",
  WARD_PURGED = "WARD_PURGED",
  WORKFLOW_CREATED = "WORKFLOW_CREATED",
  WORKFLOW_UPDATED = "WORKFLOW_UPDATED",
  WORKFLOW_ACTIVATED = "WORKFLOW_ACTIVATED",
  WORKFLOW_DEACTIVATED = "WORKFLOW_DEACTIVATED",
  WORKFLOW_SOFT_DELETED = "WORKFLOW_SOFT_DELETED",
  WORKFLOW_RESTORED = "WORKFLOW_RESTORED",
  WORKFLOW_PURGED = "WORKFLOW_PURGED",
  TRANSITION_APPROVED = "TRANSITION_APPROVED",
  TRANSITION_REJECTED = "TRANSITION_REJECTED",
  LOGIN_SUCCESS = "LOGIN_SUCCESS",
  LOGIN_FAILED = "LOGIN_FAILED",
  PASSWORD_RESET_REQUESTED = "PASSWORD_RESET_REQUESTED",
  PASSWORD_RESET_COMPLETED = "PASSWORD_RESET_COMPLETED",
  ROLE_PREVIEW_ENTERED = "ROLE_PREVIEW_ENTERED",
  ROLE_PREVIEW_EXITED = "ROLE_PREVIEW_EXITED",
}

export enum ActorType {
  USER = "USER",
  SYSTEM = "SYSTEM",
  ANONYMOUS = "ANONYMOUS",
}

export interface AuditEvent {
  action: AuditAction;
  entityType: string;
  entityId: string;
  actorId?: string;
  actorType: ActorType;
  actorName?: string;
  metadata?: Record<string, unknown>;
  timestamp: Date;
}

export interface AuditService {
  log(event: Omit<AuditEvent, "timestamp">): Promise<void>;
}
